### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by MoritzKeppler** [cloudbase/garm-provider-openstack#4]
Are the sources in this repo also released under Apache2?
If so it would be great if a licensefile would be added.

Thanks a lot!
<sub> Moritz Keppler <moritz.keppler@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by gabriel-samfira** [comment]
Yes. Apache 2.0 as well. I always forget to add the license.
